name: CICD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    env:
      GO111MODULE: auto
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.0'
    
    - name: Install dependencies
      run: |
        go version
        
    - name: Run build
      run: |
        mkdir -p /home/runner/go/src/
        mv ex_3 /home/runner/go/src/
        cd /home/runner/go/src/ex_3 && go mod download
        go build /home/runner/go/src/ex_3/cmd/main.go
